### ISSUE TITLE
Rendering of nested blocks inside an alternative

### ISSUE THREAD

**Issue by th7nder** [ZenUml/jetbrains-zenuml#113] opened 2020-04-06 17:53 UTC
```Guest
RegisterPage
AccountController
AccountService
AccountFacade
@Starter(Guest)
if (validAccountData) {
  display_success = RegisterPage.register(account) {
    successful_response = AccountController.register(account) {
      // RW, Read Commited
      while(1) {
        success = AccountService.register(account) {
          success = AccountFacade.create(account)
        }
      }
      MailSender.sendConfirmationMail()
    }
  }
} else if (loginExists) {
  display_error = RegisterPage.register(account) {
    error_account_exists = AccountController.register(account) {
      // RW, Read Commited
      while(1) {
        failure = AccountService.register(account) {
          account_exists = AccountFacade.create(account)
        }
      }
    }
  }
} else if (invalidData) {
  display_error = RegisterPage.register(account) {
    error_invalid_data = AccountController.register(account)
  }
}
```

On webpage:

![image](https://user-images.githubusercontent.com/8305170/78589097-f3655a80-783f-11ea-9ff8-e8409376b864.png)

In the IntelliJ: 
![image](https://user-images.githubusercontent.com/8305170/78589238-2f002480-7840-11ea-9e89-07810a42d598.png)

View changes as I am changing window size.
MacOS 10.15.3 Catalina

**Comment by MrCoder** [comment] 2020-04-06 23:08
Hi @th7nder, thanks for reporting this. This is a known issue on some JDK versions. The issue is that the javafx WebView released with those version cannot render nested DOMs properly in some cases. What I can suggest is to upgrade to the latest Intellij and use it own JRB if possible.

Can you please try and let us know if it still happens？

**Comment by th7nder** [comment] 2020-04-07 06:57
Hi @MrCoder, thanks for the quick response. I've upgraded my IntelliJ to latest (2019.3.4) and changed JDK to different ones (Jetbrains, Oracle, OpenJDK). I'm afraid that it does not work properly either, same issue.

**Comment by MrCoder** [comment] 2020-05-05 07:19
Hi @th7nder , sorry for replying late. I am afraid I mixed this with another rendering related issue. We do not have a solution for this issue. We are pretty sure this is JavaFx related, because we have tested with the same HTML on browsers and JavaFx WebView. That is why we have provided an "Open in Browser" as a workaround.
We will keep looking for solutions.

**Comment by MrCoder** [comment] 2022-02-22 10:56
Hi @th7nder , I understand this is a very late reply. But this has been fixed. We have removed the dependency on JavaFx and replaced it with JCEF. Thanks.

**Closed by MrCoder** 2022-02-22 10:56 UTC
Labels: help wanted
